export const INDONESIAN_CITIES = [
  "Jakarta",
  "Surabaya",
  "Bandung",
  "Medan",
  "Semarang",
  "Makassar",
  "Palembang",
  "Tangerang",
  "Depok",
  "Bekasi",
  "Bogor",
  "Yogyakarta",
  "Malang",
  "Denpasar",
  "Padang",
  "Pekanbaru",
  "Banjarmasin",
  "Samarinda",
  "Pontianak",
  "Manado",
  "Balikpapan",
  "Batam",
  "Solo (Surakarta)",
  "Cirebon",
  "Aceh (Banda Aceh)",
];
