/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthenticatedWaitingRouteImport } from './routes/_authenticated.waiting'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated.matches'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBannedRouteImport } from './routes/_authenticated.banned'
import { Route as AuthenticatedProfileMeRouteImport } from './routes/_authenticated.profile.me'
import { Route as AuthenticatedProfileIdRouteImport } from './routes/_authenticated.profile.$id'
import { Route as AuthenticatedOnboardingStep4RouteImport } from './routes/_authenticated.onboarding.step-4'
import { Route as AuthenticatedOnboardingStep3RouteImport } from './routes/_authenticated.onboarding.step-3'
import { Route as AuthenticatedOnboardingStep2RouteImport } from './routes/_authenticated.onboarding.step-2'
import { Route as AuthenticatedOnboardingStep1RouteImport } from './routes/_authenticated.onboarding.step-1'
import { Route as AuthenticatedChatMatchIdRouteImport } from './routes/_authenticated.chat.$matchId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminKycRouteImport } from './routes/_authenticated.admin.kyc'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWaitingRoute = AuthenticatedWaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBannedRoute = AuthenticatedBannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileMeRoute = AuthenticatedProfileMeRouteImport.update({
  id: '/profile/me',
  path: '/profile/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIdRoute = AuthenticatedProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingStep4Route =
  AuthenticatedOnboardingStep4RouteImport.update({
    id: '/onboarding/step-4',
    path: '/onboarding/step-4',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingStep3Route =
  AuthenticatedOnboardingStep3RouteImport.update({
    id: '/onboarding/step-3',
    path: '/onboarding/step-3',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingStep2Route =
  AuthenticatedOnboardingStep2RouteImport.update({
    id: '/onboarding/step-2',
    path: '/onboarding/step-2',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingStep1Route =
  AuthenticatedOnboardingStep1RouteImport.update({
    id: '/onboarding/step-1',
    path: '/onboarding/step-1',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatMatchIdRoute =
  AuthenticatedChatMatchIdRouteImport.update({
    id: '/chat/$matchId',
    path: '/chat/$matchId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminKycRoute = AuthenticatedAdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/banned': typeof AuthenticatedBannedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/waiting': typeof AuthenticatedWaitingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/onboarding/step-1': typeof AuthenticatedOnboardingStep1Route
  '/onboarding/step-2': typeof AuthenticatedOnboardingStep2Route
  '/onboarding/step-3': typeof AuthenticatedOnboardingStep3Route
  '/onboarding/step-4': typeof AuthenticatedOnboardingStep4Route
  '/profile/$id': typeof AuthenticatedProfileIdRoute
  '/profile/me': typeof AuthenticatedProfileMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/banned': typeof AuthenticatedBannedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/waiting': typeof AuthenticatedWaitingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/onboarding/step-1': typeof AuthenticatedOnboardingStep1Route
  '/onboarding/step-2': typeof AuthenticatedOnboardingStep2Route
  '/onboarding/step-3': typeof AuthenticatedOnboardingStep3Route
  '/onboarding/step-4': typeof AuthenticatedOnboardingStep4Route
  '/profile/$id': typeof AuthenticatedProfileIdRoute
  '/profile/me': typeof AuthenticatedProfileMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/banned': typeof AuthenticatedBannedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/waiting': typeof AuthenticatedWaitingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/_authenticated/onboarding/step-1': typeof AuthenticatedOnboardingStep1Route
  '/_authenticated/onboarding/step-2': typeof AuthenticatedOnboardingStep2Route
  '/_authenticated/onboarding/step-3': typeof AuthenticatedOnboardingStep3Route
  '/_authenticated/onboarding/step-4': typeof AuthenticatedOnboardingStep4Route
  '/_authenticated/profile/$id': typeof AuthenticatedProfileIdRoute
  '/_authenticated/profile/me': typeof AuthenticatedProfileMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/banned'
    | '/dashboard'
    | '/matches'
    | '/settings'
    | '/waiting'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/kyc'
    | '/admin/users'
    | '/chat/$matchId'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/profile/$id'
    | '/profile/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/banned'
    | '/dashboard'
    | '/matches'
    | '/settings'
    | '/waiting'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/kyc'
    | '/admin/users'
    | '/chat/$matchId'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/profile/$id'
    | '/profile/me'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/privacy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/banned'
    | '/_authenticated/dashboard'
    | '/_authenticated/matches'
    | '/_authenticated/settings'
    | '/_authenticated/waiting'
    | '/auth/login'
    | '/auth/signup'
    | '/_authenticated/admin/kyc'
    | '/_authenticated/admin/users'
    | '/_authenticated/chat/$matchId'
    | '/_authenticated/onboarding/step-1'
    | '/_authenticated/onboarding/step-2'
    | '/_authenticated/onboarding/step-3'
    | '/_authenticated/onboarding/step-4'
    | '/_authenticated/profile/$id'
    | '/_authenticated/profile/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/waiting': {
      id: '/_authenticated/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof AuthenticatedWaitingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/banned': {
      id: '/_authenticated/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof AuthenticatedBannedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/me': {
      id: '/_authenticated/profile/me'
      path: '/profile/me'
      fullPath: '/profile/me'
      preLoaderRoute: typeof AuthenticatedProfileMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/$id': {
      id: '/_authenticated/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AuthenticatedProfileIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/step-4': {
      id: '/_authenticated/onboarding/step-4'
      path: '/onboarding/step-4'
      fullPath: '/onboarding/step-4'
      preLoaderRoute: typeof AuthenticatedOnboardingStep4RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/step-3': {
      id: '/_authenticated/onboarding/step-3'
      path: '/onboarding/step-3'
      fullPath: '/onboarding/step-3'
      preLoaderRoute: typeof AuthenticatedOnboardingStep3RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/step-2': {
      id: '/_authenticated/onboarding/step-2'
      path: '/onboarding/step-2'
      fullPath: '/onboarding/step-2'
      preLoaderRoute: typeof AuthenticatedOnboardingStep2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/step-1': {
      id: '/_authenticated/onboarding/step-1'
      path: '/onboarding/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof AuthenticatedOnboardingStep1RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$matchId': {
      id: '/_authenticated/chat/$matchId'
      path: '/chat/$matchId'
      fullPath: '/chat/$matchId'
      preLoaderRoute: typeof AuthenticatedChatMatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/kyc': {
      id: '/_authenticated/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AuthenticatedAdminKycRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBannedRoute: typeof AuthenticatedBannedRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWaitingRoute: typeof AuthenticatedWaitingRoute
  AuthenticatedAdminKycRoute: typeof AuthenticatedAdminKycRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedChatMatchIdRoute: typeof AuthenticatedChatMatchIdRoute
  AuthenticatedOnboardingStep1Route: typeof AuthenticatedOnboardingStep1Route
  AuthenticatedOnboardingStep2Route: typeof AuthenticatedOnboardingStep2Route
  AuthenticatedOnboardingStep3Route: typeof AuthenticatedOnboardingStep3Route
  AuthenticatedOnboardingStep4Route: typeof AuthenticatedOnboardingStep4Route
  AuthenticatedProfileIdRoute: typeof AuthenticatedProfileIdRoute
  AuthenticatedProfileMeRoute: typeof AuthenticatedProfileMeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBannedRoute: AuthenticatedBannedRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWaitingRoute: AuthenticatedWaitingRoute,
  AuthenticatedAdminKycRoute: AuthenticatedAdminKycRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedChatMatchIdRoute: AuthenticatedChatMatchIdRoute,
  AuthenticatedOnboardingStep1Route: AuthenticatedOnboardingStep1Route,
  AuthenticatedOnboardingStep2Route: AuthenticatedOnboardingStep2Route,
  AuthenticatedOnboardingStep3Route: AuthenticatedOnboardingStep3Route,
  AuthenticatedOnboardingStep4Route: AuthenticatedOnboardingStep4Route,
  AuthenticatedProfileIdRoute: AuthenticatedProfileIdRoute,
  AuthenticatedProfileMeRoute: AuthenticatedProfileMeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
